# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geo-Demo-Zipskinny
version:      0.01
version_from: lib/Geo/Demo/Zipskinny.pm
installdirs:  site
requires:
    LWP::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
